"""Type stubs for the Rust extension module."""

from typing import Iterable, Optional, Sequence

__version__: str

Point = tuple[float, float, float]

class Lane:
    """One lane of a road's cross-section."""

    def __init__(
        self,
        width: float,
        direction: str = "forward",
        type_: str = "driving",
        speed_limit_kph: Optional[float] = None,
        side: Optional[str] = None,
        left_marking: str = "solid",
        right_marking: str = "solid",
        marking_color: str = "white",
        width_profile: Optional[Sequence[tuple[float, float]]] = None,
        taper: str = "linear",
    ) -> None: ...
    @property
    def width(self) -> float: ...
    @property
    def width_profile(self) -> list[tuple[float, float]]: ...
    @property
    def direction(self) -> str: ...
    @property
    def type_(self) -> str: ...

class LaneRef:
    """A reference to one lane of one road."""

    @property
    def road(self) -> str: ...
    @property
    def index(self) -> int: ...
    @property
    def id(self) -> str: ...

class Road:
    """A handle on a road that has been added to a map."""

    @property
    def id(self) -> str: ...
    @property
    def lane_count(self) -> int: ...
    def lane(self, index: int) -> LaneRef: ...
    def lanes(self) -> list[LaneRef]: ...

class Junction:
    """A handle on a junction."""

    @property
    def id(self) -> str: ...

class Alignment:
    """A road alignment built one piece at a time."""

    def __init__(self, start: Point, heading: float = 0.0) -> None: ...
    def line(self, length: float, rise: float = 0.0) -> None: ...
    def arc(self, length: float, curvature: float, rise: float = 0.0) -> None: ...
    def spiral(
        self, length: float, curvature_end: float, rise: float = 0.0
    ) -> None: ...
    @property
    def point(self) -> Point: ...
    @property
    def heading(self) -> float: ...
    @property
    def curvature(self) -> float: ...

class Map:
    """A road network under construction."""

    def __init__(
        self,
        name: Optional[str] = None,
        origin: Optional[Point] = None,
        projection: str = "local_cartesian",
        handedness: str = "rht",
        sampling: float = 2.0,
    ) -> None: ...
    def add_road(
        self,
        lanes: Sequence[Lane],
        start: Optional[Point] = None,
        end: Optional[Point] = None,
        points: Optional[Iterable[Point]] = None,
        alignment: Optional[Alignment] = None,
        name: Optional[str] = None,
        type_: str = "town",
        speed_limit_kph: Optional[float] = None,
        superelevation: Optional[Sequence[tuple[float, float]]] = None,
        cross_sections: Optional[Sequence[tuple[float, Sequence[Lane]]]] = None,
    ) -> Road: ...
    def add_junction(self, name: Optional[str] = None) -> Junction: ...
    def connect(
        self, a: Road, b: Road, junction: Optional[Junction] = None
    ) -> list[tuple[str, str]]: ...
    def connect_lanes(
        self, from_lane: LaneRef, to_lane: LaneRef, junction: Optional[Junction] = None
    ) -> str: ...
    def add_stop_line(self, lane: LaneRef, end: str = "end") -> str: ...
    def add_traffic_light(
        self, lane: LaneRef, end: str = "end", height: float = 5.0
    ) -> str: ...
    def add_traffic_sign(
        self, lane: LaneRef, code: str, end: str = "end", height: float = 2.5
    ) -> str: ...
    def add_crosswalk(
        self, road: Road, fraction: float = 0.5, width: float = 4.0
    ) -> str: ...
    def add_traffic_light_rule(
        self,
        lights: Sequence[str],
        lanes: Sequence[LaneRef],
        stop_line: Optional[str] = None,
    ) -> None: ...
    def add_right_of_way(
        self,
        right_of_way: Sequence[LaneRef],
        yielding: Sequence[LaneRef],
        stop_line: Optional[str] = None,
    ) -> None: ...
    def add_speed_limit(self, lanes: Sequence[LaneRef], kph: float) -> None: ...
    def validate(self) -> None: ...
    def issues(self) -> list[str]: ...
    def format_warnings(self) -> list[str]: ...
    def export_opendrive(self, path: str) -> None: ...
    def export_lanelet2(self, path: str) -> None: ...
    def to_opendrive_xml(self) -> str: ...
    def to_lanelet2_osm(self) -> str: ...
    def road_ids(self) -> list[str]: ...
    def lane_ids(self) -> list[str]: ...
    def connections(self) -> list[tuple[str, str]]: ...
    def successors(self, lane: str) -> list[str]: ...
    def lane_centerline(self, lane: str) -> list[Point]: ...
