//! A very small XML document, because a SUMO plain file is a very small format.
//!
//! Every element is attributes on a flat tag and nothing else — no text, no mixed
//! content, one level of nesting at most. What is borrowed from `quick-xml` is the
//! escaping and the indentation; there is no data model here worth deriving.

use quick_xml::events::{BytesDecl, BytesEnd, BytesStart, BytesText, Event};
use quick_xml::Writer;

/// The document is built in memory, and writing to a `Vec<u8>` has no failure mode
/// to report — so the writer's `io::Result` is unwrapped here rather than carried up
/// through every element.
const INFALLIBLE: &str = "writing XML into a string cannot fail";

pub(crate) struct Document {
    writer: Writer<Vec<u8>>,
    root: &'static str,
}

impl Document {
    /// Opens a document whose root is `root`, declaring the SUMO schema it follows.
    ///
    /// The schema location is what lets netconvert validate the file before it reads
    /// it — with `SUMO_HOME` set it is checked against the local copy, so a mistake
    /// here is a parse error rather than a network that quietly differs.
    pub fn new(root: &'static str, schema: &str) -> Document {
        let mut writer = Writer::new_with_indent(Vec::new(), b' ', 4);
        writer
            .write_event(Event::Decl(BytesDecl::new("1.0", Some("UTF-8"), None)))
            .expect(INFALLIBLE);
        writer
            .write_event(Event::Comment(BytesText::new(
                " generated by roadgen from the canonical road IR ",
            )))
            .expect(INFALLIBLE);
        let mut element = BytesStart::new(root);
        element.push_attribute(("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance"));
        element.push_attribute(("xsi:noNamespaceSchemaLocation", schema));
        writer.write_event(Event::Start(element)).expect(INFALLIBLE);
        Document { writer, root }
    }

    /// An element with no children.
    pub fn leaf(&mut self, name: &str, attributes: &[(&str, String)]) {
        self.writer
            .write_event(Event::Empty(element(name, attributes)))
            .expect(INFALLIBLE);
    }

    pub fn open(&mut self, name: &str, attributes: &[(&str, String)]) {
        self.writer
            .write_event(Event::Start(element(name, attributes)))
            .expect(INFALLIBLE);
    }

    pub fn close(&mut self, name: &str) {
        self.writer
            .write_event(Event::End(BytesEnd::new(name)))
            .expect(INFALLIBLE);
    }

    pub fn finish(mut self) -> String {
        self.writer
            .write_event(Event::End(BytesEnd::new(self.root)))
            .expect(INFALLIBLE);
        let mut xml = String::from_utf8(self.writer.into_inner())
            .expect("quick-xml writes UTF-8 into the buffer it was given");
        xml.push('\n');
        xml
    }
}

fn element<'a>(name: &'a str, attributes: &'a [(&'a str, String)]) -> BytesStart<'a> {
    let mut element = BytesStart::new(name);
    for (key, value) in attributes {
        element.push_attribute((*key, value.as_str()));
    }
    element
}
